name: Build sdv-flow package

concurrency:
  group: build-sdv-flow-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - lianyou-master
      - uisee-master
    tags:
      - '*'
  pull_request:
    branches:
      - sdv_master
  release:
    types:
      - published
    branches:
      - sdv_master


jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # By default, actions/checkout performs a shallow clone, which might not include all tags.
        with:
          fetch-depth: 0 # Fetch all history including tags
      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Build Docker Images
        run: |
          docker build -t nanomq_with_parquet_amd64 -f deploy/lianyou-deploy/Dockerfile .
          docker build -t nanomq_with_parquet_arm64 -f deploy/lianyou-deploy/Dockerfile-arm64 .

      - name: Package Artifacts
        run: |
          pkgversion="$(git describe --abbrev=1 --tags)"
          git log --format=%H -1 > readme.txt
          cd nng && git log --format=%H -1 >> ../readme.txt && cd -
          
          for arch in amd64 arm64; do
            mkdir -p packages/nanomq/{parquet,etc,log} packages/nanomq-debug/{parquet,etc,log}
            id=$(docker create nanomq_with_parquet${arch:+_$arch})
            docker cp $id:/opt/NanoMQ_mirror/build/nanomq/nanomq ./packages/nanomq/
            docker cp $id:/opt/NanoMQ_mirror/build-debug/nanomq/nanomq ./packages/nanomq-debug/
            cp readme.txt ./packages/nanomq/
            cp readme.txt ./packages/nanomq-debug/
            cp etc/nanomq.conf ./packages/nanomq/etc
            cp etc/nanomq.conf ./packages/nanomq-debug/etc
            
            cd ./packages
            tar -zcvf ./nanomq-${pkgversion}-linux-${arch}-sdv.tar.gz ./nanomq
            tar -zcvf ./nanomq-${pkgversion}-linux-${arch}-debug-sdv.tar.gz ./nanomq-debug
            cp ../etc/nanomq_geely.conf ./nanomq/etc/nanomq.conf
            cp ../etc/nanomq_geely.conf ./nanomq-debug/etc/nanomq.conf
            tar -zcvf ./nanomq-${pkgversion}-linux-${arch}-geely.tar.gz ./nanomq
            tar -zcvf ./nanomq-${pkgversion}-linux-${arch}-debug-geely.tar.gz ./nanomq-debug

            rm -rf ./nanomq ./nanomq-debug
            docker rm -v $id
            cd -
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NanoMQ Packages
          path: packages/*.tar.gz
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          token: ${{ github.token }}
          name: NanoMQ ${{ github.ref_name }} Released
          files: packages/*.tar.gz