name: Build lianyou package

concurrency:
  group: build-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - lianyou-master
  pull_request:
    branches:
      - lianyou-master
  release:
    types:
    - published

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          name: lianyou-master
      - run: |
          git submodule update --init --recursive
          cd nng && git checkout moi_master_1228
      - run: docker build -t nanomq_with_parquet -f deploy/lianyou-deploy/Dockerfile .
      - run: |
          mkdir packages
          git log -1 >> packages/readme.txt
          cd nng && git log -1 >> ../packages/readme.txt && cd -
          id=$(docker create nanomq_with_parquet)
          docker cp $id:/opt/NanoMQ_mirror/build/nanomq/nanomq packages/nanomq
          docker cp $id:/opt/NanoMQ_mirror/build-debug/nanomq/nanomq packages/nanomq-debug
          docker rm -v $id
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/
          retention-days: 7
