name: Build sdv-flow package

concurrency:
  group: build-sdv-flow-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - lianyou-master
    tags:
      - '*'
  pull_request:
    branches:
      - sdv_master
  release:
    types:
      - published
    branches:
      - sdv_master


jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: |
          git submodule update --init --recursive
          # cd nng && git checkout sdv_master
      - run: docker build -t nanomq_with_parquet -f deploy/lianyou-deploy/Dockerfile .
      - run: docker build -t nanomq_with_parquet_arm64 -f deploy/lianyou-deploy/Dockerfile-arm64 .
      - run: |
          mkdir -p packages/nanomq/parquet packages/nanomq-debug/parquet
          mkdir -p packages/nanomq/etc packages/nanomq-debug/etc
          mkdir -p packages/nanomq/log packages/nanomq-debug/log
          pkgversion="$(git describe --abbrev=0 --tags | tr '-' '_')"
          git log -1 >> readme.txt
          cd nng && git log -1 >> ../readme.txt && cd -
          id=$(docker create nanomq_with_parquet)
          docker cp $id:/opt/NanoMQ_mirror/build/nanomq/nanomq ./packages/nanomq/
          docker cp $id:/opt/NanoMQ_mirror/build-debug/nanomq/nanomq ./packages/nanomq-debug/
          cp readme.txt ./packages/nanomq/
          cp readme.txt ./packages/nanomq-debug/
          cp etc/nanomq.conf ./packages/nanomq/etc
          cp etc/nanomq.conf ./packages/nanomq-debug/etc
          cd ./packages
          tar -zcvf ./nanomq-${pkgversion}-linux-amd64.tar.gz ./nanomq
          tar -zcvf ./nanomq-${pkgversion}-linux-amd64-debug.tar.gz ./nanomq-debug
          rm -rf ./nanomq/nanomq ./nanomq-debug/nanomq
          docker rm -v $id

          id=$(docker create nanomq_with_parquet_arm64)
          docker cp $id:/opt/NanoMQ_mirror/build/nanomq/nanomq ./nanomq/
          docker cp $id:/opt/NanoMQ_mirror/build-debug/nanomq/nanomq ./nanomq-debug/
          tar -zcvf ./nanomq-${pkgversion}-linux-arm64.tar.gz ./nanomq/
          tar -zcvf ./nanomq-${pkgversion}-linux-arm64-debug.tar.gz ./nanomq-debug/
          rm -rf ./nanomq ./nanomq-debug
          docker rm -v $id

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/*.tar.gz
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          token: ${{ github.token }}
          name: NanoMQ ${{ github.ref_name }} Released
          files: packages/*.tar.gz
